### ISSUE TITLE
`cf jobs` is not a registered command

### ISSUE THREAD

**Issue by Sannidhi** [pivotal-cf/docs-scheduler#3]
Using the scheduler for the first time and followed the docs here: http://docs.pivotal.io/pcf-scheduler/using.html#list-jobs 

```cf jobs``` does not seem to be a registered command. When I looked on cf help in the cli and searched for "jobs" "tasks" or "schedule" no commands came up. I tired `cf create-job` as well but got the same result. 

![screen shot 2017-05-23 at 10 30 05 am](https://cloud.githubusercontent.com/assets/1033737/26345318/d3b3ebc6-3fa2-11e7-9131-db445c58a5a2.png)

**Comment by ljarzynski** [comment]
@slhommed Would you be able to help @Sannidhi troubleshoot?

**Comment by ghanna2017** [comment]
Hi @slhommed Were you able to help on this? Not sure why it was closed and reopened.

Thanks, Gigi

**Comment by slhommed** [comment]
HI all, I didn't see this until now.  I did talk to @Sannidhi on slack and I understand the problems have been resolved.  
There may still be a docs issue we need to address.

**Comment by Sannidhi** [comment]
@slhommed @ghanna2017 I was able to resolve the command not found issue for `cf jobs` when I downloaded the cli plugin that Scott pointed me to. 

However I still see that `cf logs "job-name"` does not work as it tries to retrieve logs for an app and not for the job. What is the correct command for this? I can create a pull request for the docs @slhommed if you can tell me the valid commands. 

Also tried to use schedule-job with the example in the docs and I get the error `Validation of resource failed. The cron expression '0 12 * * * ' is invalid.` 

Closing this one as the two issues I mentioned are unrelated to this.

**Comment by slhommed** [comment]
Hi All, All the commands referenced in the docs require the CLI Plugin.  The plugin is available as a download on Pivotal Network alongside the Scheduler For PCF Tile.

The logs for any job can be found by using the `cf logs <app_name>` command, where app_name is the name of the app the job is related to.

The issue with the invalid schedule is due to the expression.  The expression requires a ? in the 3rd or 5th position.  We'll be adding an entire section in the docs for expression formatting.

Also, sorry for the delays.  The notifications for this repo were not getting to my inbox.

**Comment by Karnakannan** [comment]
Hi, I've bind Scheduler PCF service to my app in PCF and created a scheduler job to start the job with command as ".java-buildpack/open_jdk_jre/bin/java org.springframework.boot.loader.JarLauncher" as of below :
1) cf create-job My-app1 my_app_sch ".java-buildpack/open_jdk_jre/bin/java org.springframework.boot.loader.JarLauncher" --done
2) cf run-job my_app_sch   --Running the job
3) In PCF logs, I'm getting error "Property sources not found error" & "java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@80503" in my app.

**Comment by jncd** [comment]
Thank you for raising this issue, and I’m sorry that you are having trouble. Please sign in to [Pivotal Support](https://pivotal.io/support) and consult the community or open a case. See [Pivotal Support for Subscribers](https://content.pivotal.io/support/pivotal-support-for-subscribers) for how to do this. If Pivotal Support’s investigation determines that this is a general problem, rather than an issue that is fairly specific to your situation, we will update the documentation.
